// <auto-generated />
namespace ProductsCatalog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addslideshow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addslideshow));
        
        string IMigrationMetadata.Id
        {
            get { return "202006242004379_add-slideshow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
